# left-side user profile
avatar: https://s2.ax1x.com/2020/02/18/3iqdzD.jpg # by default https://octodex.github.com/images/baracktocat.jpg
location:
email: momonorthy2008@outlook.com
social:
  github: https://github.com/momonorthy
  weibo:
  linkedin:

# navbar menu
menu:
 archives: true
 tags: true
 categories: true

rss_dir: atom.xml

# widget
ga: # google analytics tracking code UA-XXXXXXX-X
baidutongji: # baidutongji tracking code
duoshuo: # duoshuo username
gcs: # google custom search code

# flagcounter
flagcounter_href: # https://info.flagcounter.com/xxxx
flagcounter_img_src: # https://s01.flagcounter.com/xxxx
# star page
#for example https://github.com/momoNorthy/momonorthy.github.com/issues/5
star: https://github.com/momoNorthy/momonorthy.github.com/issues/5
starcount: 1
forklocation: https://github.com/m3blog/hexo-theme-replicapp/fork
forkcount: 0